package dempred.datastructure;

import dempred.featuregeneration.FeatureGeneratorInterface;
import dempred.math.DenseVector;

/**
 * A utility class which contains several functions to manipulate a single datapoint
 */
public class DatapointManipulator {

	/**
	 * Adds additional features to a given datapoint which are generated by a featureGenerator
	 * 
	 * @param <T>
	 *            all classes which extend datapoint
	 * @param datapoint
	 *            the datapoint which should be extendet by new features
	 * @param featureGenerator
	 *            the feature generator which should be used
	 * @throws Exception
	 *             the exception
	 */
	public static <T extends Datapoint> void addFeatures(T datapoint, FeatureGeneratorInterface<T> featureGenerator) throws Exception {
		double[] oldFeatures = datapoint.getFeatureVector().getElements();
		double[] newFeatures = featureGenerator.generateFeature(datapoint);
		double[] features = new double[oldFeatures.length + newFeatures.length];
		System.arraycopy(oldFeatures, 0, features, 0, oldFeatures.length);
		System.arraycopy(newFeatures, 0, features, oldFeatures.length, newFeatures.length);
		datapoint.setFeatureVector(new DenseVector(features));
	}
}
